// npm i react-icons
// npm i classnames //A simple JavaScript utility for conditionally joining classNames together.
// npm i prisma@5.3.1 // npx prisma init for the first amount
// npm i zod@3.22.2 for the data-validation
// npm i @radix-ui/themes // for the beutifull built in components
// npm install --save react-simplemde-editor easymde // this is for the editor
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="violet">
          <NavBar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
